### ISSUE TITLE
support png images as input

### ISSUE THREAD

**Issue by catdad** [catdad-experiments/to-bmp#3]

**Comment by NeeEoo** [comment]
Should it support transparency? (alpha)

**Comment by catdad** [comment]
Well, I am pretty sure that the BMP encoder already supports transparency, so this story is really about adding a PNG decoder to the library and exposing it through all the necessary options. That is to say, I am pretty sure transparency already works as long as the source image can have it

**Comment by NeeEoo** [comment]
When i tried with a transparent png it looked like this
(Had to zip since github doesn't support bmp)
[test.bmp.zip](https://github.com/catdad-experiments/to-bmp/files/5359665/test.bmp.zip)

**Comment by NeeEoo** [comment]
I am unable to get transparency to work. Even when setting `bitPP: 32` on the Encoder settings doesn't fix it.

**Comment by catdad** [comment]
Published in 1.1.0
